/* cobra_ver.h */

/*+++ *******************************************************************\
*
*   Copyright and Disclaimer:
*
*       ---------------------------------------------------------------
*       ALL SOFTWARE, APPLICATIONS, DOCUMENTATION, OR MATERIALS
*       FURNISHED HEREIN IS PROVIDED *AS IS*.  CONEXANT DOES NOT MAKE
*       ANY WARRANTIES, EITHER EXPRESS OR IMPLIED, AND HEREBY EXPRESSLY
*       DISCLAIMS ANY AND ALL SUCH WARRANTIES TO THE EXTENT PERMITTED
*       BY LAW, INCLUDING, SPECIFICALLY, ANY IMPLIED WARRANTY ARISING
*       BY STATUTE OR OTHERWISE IN LAW OR FROM A COURSE OF DEALING OR
*       USAGE OF TRADE.  CONEXANT DOES NOT MAKE ANY WARRANTIES, EITHER
*       EXPRESS OR IMPLIED, AND HEREBY EXPRESSLY DISCLAIMS ANY AND ALL
*       SUCH WARRANTIES WITH RESPECT TO ALL SOFTWARE, APPLICATIONS,
*       DOCUMENTATION, AND MATERIALS INCLUDING ALL IMPLIED WARRANTIES
*       OF MERCHANTABILITY, OR OF MERCHANTABLE QUALITY, OR OF FITNESS
*       FOR ANY PURPOSE, PARTICULAR, SPECIFIC OR OTHERWISE, OR OF
*       NONINFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS OF OTHERS,
*       RELATING TO THE SOFTWARE, APPLICATIONS, OPERATION,
*       DOCUMENTATION, DATA OR RESULTS GENERATED BY THE OPERATION OR
*       USE THEREOF, AND MATERIALS PROVIDED HEREIN.  THE ENTIRE RISK AS
*       TO THE SUBSTANCE, QUALITY AND PERFORMANCE OF SOFTWARE,
*       APPLICATIONS, AND DOCUMENTATION DESCRIBING SUCH SOFTWARE
*       REMAINS WITH THE BUYER.
*
*       REGARDLESS OF WHETHER ANY REMEDY SET FORTH HEREIN FAILS OF ITS
*       ESSENTIAL PURPOSE OR OTHERWISE, CONEXANT SHALL NOT BE LIABLE
*       FOR ANY EXEMPLARY, SPECIAL, PUNITIVE, SPECULATIVE, INDIRECT,
*       CONSEQUENTIAL OR INCIDENTAL DAMAGES OF ANY KIND (INCLUDING
*       WITHOUT LIMITATION LOST PROFITS, LOSS OF INCOME, LOSS OF
*       GOODWILL, OR OTHER TANGIBLE OR INTANGIBLE BUSINESS LOSS)
*       ARISING OUT OF OR IN CONNECTION WITH, DIRECTLY OR INDIRECTLY,
*       SOFTWARE, APPLICATIONS, DOCUMENTATION, OR ANY SERVICES OR
*       MATERIALS PROVIDED HEREUNDER, OR USE OR INABILITY TO USE THE
*       SOFTWARE, EVEN IF CONEXANT HAS BEEN ADVISED OF THE POSSIBILITY
*       OF SUCH DAMAGES.
*
*       Copyright (c) 2001 Conexant Systems, Inc.
*       All Rights Reserved.
*       ---------------------------------------------------------------
*
*   Module Revision Id:
*
*       $Header: cobra_ver.h, 5, 3/16/04 11:49:29 AM, Billy Jackman$
*
*   Abstract:
*
*       Cobra version-specific data.
*
\******************************************************************* ---*/

#ifndef COBRA_VER_H_DEFINED
#define COBRA_VER_H_DEFINED

/*******************************************************************************************************/
/* version info */
/*******************************************************************************************************/

#define VERSION_MAJOR 2
#define VERSION_RELEASE 5
#define VERSION_BUILD 3
#define VERSION_MINOR 0

#define PRODUCT_NAME_STRING        ("CX24130")               /* 130 */
#define PRODUCT_NAME_STRING_ALT    ("CX24121")               /* 121 */

#define PRODUCT_NAME_STRING_CAM64  ("CX24123")               /* 123 */
#define PRODUCT_NAME_STRING_CAM80  ("CX24123C")              /* 123C (Cobra-compat) */
#define PRODUCT_NAME_STRING_UCOB80 ("CX24130U")              /* 130U (UMC Cobra-compat) */
#define PRODUCT_NAME_STRING_CAMARO ("CX2415X")               /* Camaro */

#define PRODUCT_VERSION_STRING "2.5.3.0"
#define FILE_VERSION_STRING "2,5,3,0"

/*******************************************************************************************************/
/*******************************************************************************************************/
/*******************************************************************************************************/
#endif  /* #ifndef COBRA_VER_H_DEFINED */
/* CR 9509 : Add an extra newline */

