/* cobra_tuner.c */

/*+++ *******************************************************************\
*
*   Copyright and Disclaimer:
*
*       ---------------------------------------------------------------
*       ALL SOFTWARE, APPLICATIONS, DOCUMENTATION, OR MATERIALS        
*       FURNISHED HEREIN IS PROVIDED *AS IS*.  CONEXANT DOES NOT MAKE  
*       ANY WARRANTIES, EITHER EXPRESS OR IMPLIED, AND HEREBY EXPRESSLY
*       DISCLAIMS ANY AND ALL SUCH WARRANTIES TO THE EXTENT PERMITTED  
*       BY LAW, INCLUDING, SPECIFICALLY, ANY IMPLIED WARRANTY ARISING  
*       BY STATUTE OR OTHERWISE IN LAW OR FROM A COURSE OF DEALING OR  
*       USAGE OF TRADE.  CONEXANT DOES NOT MAKE ANY WARRANTIES, EITHER 
*       EXPRESS OR IMPLIED, AND HEREBY EXPRESSLY DISCLAIMS ANY AND ALL 
*       SUCH WARRANTIES WITH RESPECT TO ALL SOFTWARE, APPLICATIONS,    
*       DOCUMENTATION, AND MATERIALS INCLUDING ALL IMPLIED WARRANTIES  
*       OF MERCHANTABILITY, OR OF MERCHANTABLE QUALITY, OR OF FITNESS  
*       FOR ANY PURPOSE, PARTICULAR, SPECIFIC OR OTHERWISE, OR OF      
*       NONINFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS OF OTHERS,     
*       RELATING TO THE SOFTWARE, APPLICATIONS, OPERATION,             
*       DOCUMENTATION, DATA OR RESULTS GENERATED BY THE OPERATION OR   
*       USE THEREOF, AND MATERIALS PROVIDED HEREIN.  THE ENTIRE RISK AS
*       TO THE SUBSTANCE, QUALITY AND PERFORMANCE OF SOFTWARE,         
*       APPLICATIONS, AND DOCUMENTATION DESCRIBING SUCH SOFTWARE       
*       REMAINS WITH THE BUYER.                                        
*                                                                      
*       REGARDLESS OF WHETHER ANY REMEDY SET FORTH HEREIN FAILS OF ITS 
*       ESSENTIAL PURPOSE OR OTHERWISE, CONEXANT SHALL NOT BE LIABLE   
*       FOR ANY EXEMPLARY, SPECIAL, PUNITIVE, SPECULATIVE, INDIRECT,   
*       CONSEQUENTIAL OR INCIDENTAL DAMAGES OF ANY KIND (INCLUDING     
*       WITHOUT LIMITATION LOST PROFITS, LOSS OF INCOME, LOSS OF       
*       GOODWILL, OR OTHER TANGIBLE OR INTANGIBLE BUSINESS LOSS)       
*       ARISING OUT OF OR IN CONNECTION WITH, DIRECTLY OR INDIRECTLY,  
*       SOFTWARE, APPLICATIONS, DOCUMENTATION, OR ANY SERVICES OR      
*       MATERIALS PROVIDED HEREUNDER, OR USE OR INABILITY TO USE THE   
*       SOFTWARE, EVEN IF CONEXANT HAS BEEN ADVISED OF THE POSSIBILITY 
*       OF SUCH DAMAGES.                                               
*
*       Copyright (c) 2001 Conexant Systems, Inc.
*       All Rights Reserved.
*       ---------------------------------------------------------------
*
*   Module Revision Id:
*
*       $Header: cobra_tuner.c, 5, 3/16/04 11:49:13 AM, Billy Jackman$
*
*   Abstract:
*
*       Front-end generic tuner interface (Demod -> Tuner)
*
\******************************************************************* ---*/

#include "cobra.h"                     /* Cobra include files, ordered */

/*******************************************************************************************************/
/* TUNER_install_CX24108() */
/*******************************************************************************************************/
BOOL  TUNER_install_CX24108(           /* Funct to install a specific (CX24108) tuner */
NIM   *nim)                            /* pointer to nim */
{
  if (nim == NULL)  return(False);

  /* initialize the various TUNER functions */
  TUNER_GetType = &_TUNER_CX24108_GetType;
  TUNER_SetType = &_TUNER_CX24108_SetType;
  TUNER_Initialize = &_TUNER_CX24108_powerup;
  TUNER_SetGainParameters = &_TUNER_CX24108_setgainparms;
  TUNER_GetPLLLockStatus = &_TUNER_CX24108_pll_status;
  TUNER_GetVCO = &_TUNER_CX24108_getvco;
  TUNER_SetReferenceDivider = &_TUNER_CX24108_SetReferenceDivider;
  TUNER_GetReferenceDivider = &_TUNER_CX24108_GetReferenceDivider;
  
  TUNER_GetVcoDivider = &_TUNER_CX24108_GetVcoDivider;

  TUNER_GetReferenceDivider = &_TUNER_CX24108_GetReferenceDivider;
  TUNER_GetPLLFrequency = &_TUNER_CX24108_GetPLLFrequency;
  TUNER_SetRegisters = &_TUNER_CX24108_set_registers;
  TUNER_GetRegisters = &_TUNER_CX24108_GetRegisters;
  TUNER_GetParameters = &_TUNER_CX24108_GetParameters;
  TUNER_SetParameters = &_TUNER_CX24108_SetParameters;
  TUNER_GetFrequency = &_TUNER_CX24108_GetFrequency;
  TUNER_SetFrequency = &_TUNER_CX24108_SetFrequency;
  TUNER_SetLastLock = &_TUNER_CX24108_SetLastLock;
  TUNER_GetLastLock = &_TUNER_CX24108_GetLastLock;
  TUNER_GetVCOEdges = &_TUNER_CX24108_GetVCOEdges;
  TUNER_SetVCOEdges = &_TUNER_CX24108_SetVCOEdges;
  TUNER_GetVCOBreakpoints = &_TUNER_CX24108_GetVCOBreakpoints;
  TUNER_SetVCOBreakpointPercentage = &_TUNER_CX24108_SetVCOBreakpointPercentage;
  TUNER_GetVCOBreakpointPercentage = &_TUNER_CX24108_GetVCOBreakpointPercentage;
  TUNER_SetFilterBandwidth = &_TUNER_CX24108_SetFilterBandwidth;
  TUNER_SetGainSettings = &_TUNER_CX24108_SetGainSettings;

  TUNER_CalculateNAR = &_TUNER_CX24108_CalculateNAR;

  /* set the TUNER type (using a function pointer) */
  if (TUNER_SetType(nim) != True)  return(False);
  
  return(True);

}  /* TUNER_install_CX24108() */


/*******************************************************************************************************/
/*******************************************************************************************************/
/*******************************************************************************************************/
/* CR 9509 : Add an extra newline */

