/*
// -----------------------------------------------------------------------
// This file is generated by the do_h_tab.pl script.
// Do NOT edit.
// -----------------------------------------------------------------------
*/

OPENTV_F(RET_1, O_rockwell_test_api, ARG_LIST  ARG_DONT_CARE ARG_POINTER )
OPENTV_F(RET_1, O_rockwell_get_config, ARG_LIST  ARG_POINTER )
OPENTV_F(RET_1, O_rockwell_set_config, ARG_LIST  ARG_POINTER )
OPENTV_F(RET_1, O_rockwell_call_native, ARG_LIST  ARG_DONT_CARE ARG_POINTER )
