/*
// -----------------------------------------------------------------------
// This file is generated by the do_h_tab.pl script.
// Do NOT edit.
// -----------------------------------------------------------------------
*/

#ifndef __OTVSAB_H__
#define __OTVSAB_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifdef __GNUC__
#define  GCC_NO_RETURN __attribute__ ((noreturn))
#else
#define  GCC_NO_RETURN
#endif

#ifndef PROTOMAK
#define zero

#define OPENTV_F(r,f,a) f##_token,

enum {
#include <otvsabt.h>
};
#undef OPENTV_F

#define PRAGMA #pragma
#define OPENTV_F(r,f,a) PRAGMA system(f, 8, f##_token)

#define otvsab_number 8

#include <otvsabt.h>

#undef OPENTV_F

#endif /* PROTOMAK */
#include "sabocode.h"
#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* __OTVSAB_H__ */

